[package]
name = "ocipa/expect"
version = "0.0.3"
authors = ["Ocipa <ocipamail@gmail.com>"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dev-dependencies]
testez = "roblox/testez@0.4.1"