[package]
name = "ocipa/expect"
version = "0.2.0"
authors = ["Ocipa <ocipamail@gmail.com>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["*.spec.lua", "README.md", "test*", "modules", "assets", "*.rbxl*"]

[dev-dependencies]